#!/bin/bash

rm -rf c-ares_git
git clone --depth=1 https://github.com/c-ares/c-ares.git c-ares_git
cd c-ares_git
autoreconf -fi
./configure --enable-static --disable-shared
make
sudo make install
cd ..
rm -rf c-ares_git