#!/bin/bash

rm -rf libexpat_git
git clone --depth=1 https://github.com/libexpat/libexpat.git libexpat_git
cd libexpat_git/expat
./buildconf.sh
./configure \
    --prefix=/usr/local/$HOST \
    --host=$HOST
    
CPUCOUNT=$(grep -c ^processor /proc/cpuinfo)
make install -j$CPUCOUNT
cd ../../
rm -rf libexpat_git 
